import { useEffect, useMemo, useState } from 'react'
import { Building2, CalendarRange, Clock, Edit3, FileText, MapPin, NotebookTabs, Trash2 } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import MapPreview, { MapButton, type MapTarget } from '../components/MapPreview'
import { ItineraryForm } from '../components/ResourceForms'
import { Badge, EmptyState, ErrorBanner, IconButton, Loading, Modal, PageHeader } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import { useTrip } from '../contexts/TripContext'
import type { City, ItineraryItem, NewItem, Reservation } from '../types'
import { formatDate } from '../utils'

export default function Itinerary(){
  const {selectedTrip}=useTrip();const tripId=selectedTrip!.id
  const {data,loading,error,reload}=useLoad(async()=>{const [items,reservations,places,cities,attachments]=await Promise.all([api.itinerary.list({trip_id:tripId}),api.reservations.list({trip_id:tripId}),api.places.list({trip_id:tripId}),api.cities.list({trip_id:tripId}),api.reservationAttachments.list(tripId)]);return {items,reservations,places,cities,attachments}})
  const [params,setParams]=useSearchParams(),navigate=useNavigate()
  const requestedCityId=Number(params.get('city_id'))||null
  const [editing,setEditing]=useState<ItineraryItem|null|undefined>(undefined),[mapTarget,setMapTarget]=useState<MapTarget|null>(null),[view,setView]=useState<'time'|'city'>(requestedCityId?'city':'time')
  useEffect(()=>{if(params.get('new')==='1'){setEditing(null);setParams({}, {replace:true})}},[params,setParams])
  useEffect(()=>{if(requestedCityId)setView('city')},[requestedCityId])
  const save=async(value:NewItem<ItineraryItem>)=>{editing?await api.itinerary.update(editing.id,value):await api.itinerary.create(value);setEditing(undefined);await reload()}
  const remove=async(item:ItineraryItem)=>{if(confirm(`确定删除“${item.title}”吗？`)){await api.itinerary.remove(item.id);await reload()}}
  if(loading)return <Loading/>;if(!data)return <ErrorBanner message={error}/>
  const cityById=new Map(data.cities.map(x=>[x.id,x]))
  const reservationById=new Map(data.reservations.map(x=>[x.id,x])),attachmentCountByReservation=new Map<number,number>();data.attachments.forEach(file=>attachmentCountByReservation.set(file.reservation_id,(attachmentCountByReservation.get(file.reservation_id)||0)+1))
  const activeCity=requestedCityId?cityById.get(requestedCityId):undefined
  const citySections=(activeCity?[activeCity]:data.cities).map(city=>[city,data.items.filter(x=>x.city_id===city.id)] as [City,ItineraryItem[]]);const unassigned=data.items.filter(x=>!x.city_id);if(!activeCity&&unassigned.length)citySections.push([null as unknown as City,unassigned])
  const clearCity=()=>{const next=new URLSearchParams(params);next.delete('city_id');setParams(next,{replace:true})}
  const showTime=()=>{setView('time');clearCity()}
  return <div><PageHeader title="城市日程" description="默认按日期和时间查看整段旅程，也可以切换成按城市归类。" action="新增日程" onAction={()=>setEditing(null)}/><ErrorBanner message={error}/>
    <div className="control-panel mb-6 flex flex-wrap items-center gap-3"><div className="inline-flex rounded-2xl bg-white p-1 shadow-sm"><button onClick={showTime} className={`flex items-center gap-2 rounded-xl px-5 py-2 text-sm font-semibold ${view==='time'?'bg-coral-500 text-white':'text-stone-500'}`}><CalendarRange size={17}/>按时间</button><button onClick={()=>setView('city')} className={`flex items-center gap-2 rounded-xl px-5 py-2 text-sm font-semibold ${view==='city'?'bg-coral-500 text-white':'text-stone-500'}`}><Building2 size={17}/>按城市</button></div>{activeCity&&view==='city'&&<div className="inline-flex items-center gap-2 rounded-2xl border border-mint-100 bg-mint-50 px-4 py-2 text-sm text-mint-600"><MapPin size={16}/><span>正在查看 <b>{activeCity.name}</b></span><button onClick={clearCity} className="ml-1 font-semibold text-stone-500 transition hover:text-coral-600">全部城市</button></div>}</div>
    {!data.items.length?<EmptyState title="还没有日程" message="从抵达、入住或第一项活动开始安排吧。" action="新增日程" onAction={()=>setEditing(null)}/>:view==='time'?<ScheduleList items={data.items} cityById={cityById} reservationById={reservationById} attachmentCountByReservation={attachmentCountByReservation} onEdit={setEditing} onDelete={remove} onMap={setMapTarget} onReservation={id=>navigate(`/reservations?id=${id}&files=1`)}/>:activeCity&&!citySections[0][1].length?<EmptyState title={`${activeCity.name}还没有日程`} message="可以新增一项日程，并把它归到这座城市。" action="新增日程" onAction={()=>setEditing(null)}/>:<div className="space-y-10">{citySections.map(([city,items])=>items.length?<section key={city?.id||'unassigned'}><div className="card mb-5 flex flex-col gap-2 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-coral-600">{city?'CITY':'CROSS CITY'}</p><h2 className="mt-1 text-2xl font-bold">{city?.name||'跨城市 / 未分组'}</h2></div>{city&&<div className="text-sm text-stone-500">{city.arrival_date&&formatDate(city.arrival_date)}{city.departure_date&&` — ${formatDate(city.departure_date)}`}</div>}</div><ScheduleList items={items} cityById={cityById} reservationById={reservationById} attachmentCountByReservation={attachmentCountByReservation} hideCity onEdit={setEditing} onDelete={remove} onMap={setMapTarget} onReservation={id=>navigate(`/reservations?id=${id}&files=1`)}/></section>:null)}</div>}
    <Modal open={editing!==undefined} title={editing?'编辑日程':'新增日程'} onClose={()=>setEditing(undefined)}><ItineraryForm key={editing?.id||'new'} item={editing} reservations={data.reservations} places={data.places} cities={data.cities} tripId={tripId} onSave={save} onCancel={()=>setEditing(undefined)}/></Modal><MapPreview target={mapTarget} onClose={()=>setMapTarget(null)}/>
  </div>
}

function ScheduleList({items,cityById,reservationById,attachmentCountByReservation,hideCity=false,onEdit,onDelete,onMap,onReservation}:{items:ItineraryItem[];cityById:Map<number,City>;reservationById:Map<number,Reservation>;attachmentCountByReservation:Map<number,number>;hideCity?:boolean;onEdit:(x:ItineraryItem)=>void;onDelete:(x:ItineraryItem)=>Promise<void>;onMap:(x:MapTarget)=>void;onReservation:(id:number)=>void}){
  const groups=useMemo(()=>items.reduce<Record<string,ItineraryItem[]>>((result,item)=>{(result[item.date]??=[]).push(item);return result},{}),[items])
  return <div className="space-y-7">{Object.entries(groups).sort(([a],[b])=>a.localeCompare(b)).map(([date,dayItems])=><div key={date}><div className="mb-3"><h3 className="font-bold">{formatDate(date,{month:'long',day:'numeric',weekday:'long'})}</h3><p className="text-xs text-stone-400">{dayItems.length} 项安排</p></div><div className="space-y-3 border-l-2 border-coral-100 pl-5 sm:pl-8">{dayItems.sort((a,b)=>a.start_time.localeCompare(b.start_time)).map(item=>{const reservation=item.reservation_id?reservationById.get(item.reservation_id):undefined,attachmentCount=item.reservation_id?attachmentCountByReservation.get(item.reservation_id)||0:0,isTicket=reservation&&['车票','机票'].includes(reservation.type);return <article key={item.id} className="card relative p-5"><span className="absolute -left-[27px] top-7 h-3 w-3 rounded-full bg-coral-500 ring-4 ring-cream sm:-left-[39px]"/><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="flex min-w-24 items-center gap-2 font-bold text-coral-600"><Clock size={16}/>{item.start_time.slice(0,5)}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="break-words text-lg font-bold">{item.title}</h4><Badge tone={item.type==='景点'?'mint':'sky'}>{item.type}</Badge>{!hideCity&&item.city_id&&<Badge tone="stone">{cityById.get(item.city_id)?.name}</Badge>}</div>{item.location&&<p className="mt-2 flex items-start gap-1.5 break-words text-sm text-stone-500"><MapPin className="mt-0.5 shrink-0" size={15}/>{item.location}</p>}{item.note&&<p className="mt-3 whitespace-pre-line text-sm leading-6 text-stone-500">{item.note}</p>}<div className="mt-4 flex flex-wrap gap-4">{item.map_url&&<MapButton target={{title:item.title,url:item.map_url,query:item.location}} onOpen={onMap}/>} {item.reservation_id&&<button className="inline-flex items-center gap-1.5 text-sm font-semibold text-coral-600" onClick={()=>onReservation(item.reservation_id!)}>{isTicket?<FileText size={15}/>:<NotebookTabs size={15}/>}查看{isTicket?`${reservation.type}文件`:'预约'}{attachmentCount?` (${attachmentCount})`:''}</button>}</div></div><div className="flex shrink-0"><IconButton aria-label="编辑" onClick={()=>onEdit(item)}><Edit3 size={17}/></IconButton><IconButton aria-label="删除" onClick={()=>void onDelete(item)}><Trash2 size={17}/></IconButton></div></div></article>})}</div></div>)}</div>
}
