import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, Edit3, FileText, MapPin, Paperclip, Search, Trash2, Upload } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import { DocumentExportActions } from '../components/DocumentExportActions'
import MapPreview, { MapButton, type MapTarget } from '../components/MapPreview'
import { ReservationForm } from '../components/ResourceForms'
import { Badge, EmptyState, ErrorBanner, IconButton, ImageCover, LinkButton, Loading, Modal, PageHeader, ReservationTypeIcon } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import { useTrip } from '../contexts/TripContext'
import type { NewItem, Reservation, ReservationAttachment, ReservationType } from '../types'
import { formatDate } from '../utils'

const coverTone:Record<ReservationType,'coral'|'mint'|'sky'|'stone'>={酒店:'coral',车票:'sky',机票:'sky',景点:'mint',餐厅:'coral',其他:'stone'}

export default function Reservations(){
  const {selectedTrip}=useTrip();const tripId=selectedTrip!.id
  const {data,loading,error,reload}=useLoad(async()=>{const [reservations,cities,attachments]=await Promise.all([api.reservations.list({trip_id:tripId}),api.cities.list({trip_id:tripId}),api.reservationAttachments.list(tripId)]);return {reservations,cities,attachments}})
  const [tab,setTab]=useState<'booked'|'pending'>('booked'),[filter,setFilter]=useState('全部'),[cityFilter,setCityFilter]=useState<number|null>(null),[query,setQuery]=useState(''),[editing,setEditing]=useState<Reservation|null|undefined>(undefined),[attachmentReservation,setAttachmentReservation]=useState<Reservation|null>(null),[mapTarget,setMapTarget]=useState<MapTarget|null>(null),[params,setParams]=useSearchParams()
  useEffect(()=>{if(params.get('new')==='1'){setEditing(null);setParams({}, {replace:true})}},[params,setParams])
  useEffect(()=>{const requested=params.get('tab');if(requested==='booked'||requested==='pending')setTab(requested)},[params])
  useEffect(()=>{const id=Number(params.get('id'));if(id&&data){const target=data.reservations.find(item=>item.id===id);if(target){setTab(target.status==='待预约'?'pending':'booked');setFilter('全部');setCityFilter(target.city_id??null);setTimeout(()=>document.getElementById(`reservation-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),50);if(params.get('files')==='1'){setAttachmentReservation(target);const next=new URLSearchParams(params);next.delete('files');setParams(next,{replace:true})}}}},[params,data,setParams])
  const normalizedQuery=query.trim().toLocaleLowerCase('zh-CN')
  const items=useMemo(()=>data?.reservations.filter(item=>{
    const matchesTab=tab==='pending'?item.status==='待预约':item.status!=='待预约'
    const haystack=[item.name,item.type,item.status,item.date,item.time,item.order_number,item.location,item.note].filter(Boolean).join(' ').toLocaleLowerCase('zh-CN')
    return matchesTab&&(filter==='全部'||item.type===filter)&&(!cityFilter||item.city_id===cityFilter)&&(!normalizedQuery||haystack.includes(normalizedQuery))
  })||[],[data,tab,filter,cityFilter,normalizedQuery])
  if(loading)return <Loading/>;if(!data)return <ErrorBanner message={error}/>
  const cityById=new Map(data.cities.map(city=>[city.id,city])),types:('全部'|ReservationType)[]=['全部','酒店','车票','机票','景点','餐厅','其他']
  const save=async(value:NewItem<Reservation>)=>{editing?await api.reservations.update(editing.id,value):await api.reservations.create(value);setEditing(undefined);await reload()}
  const remove=async(item:Reservation)=>{if(confirm(`确定删除“${item.name}”吗？`)){await api.reservations.remove(item.id);await reload()}}
  const mark=async(item:Reservation)=>{const {id:_,...payload}=item;await api.reservations.update(item.id,{...payload,status:'已预约'});await reload()}
  const changeTab=(next:'booked'|'pending')=>{setTab(next);const nextParams=new URLSearchParams(params);nextParams.set('tab',next);nextParams.delete('id');setParams(nextParams,{replace:true})}
  const exportTable={title:`${selectedTrip!.name} · 预约信息`,description:`${tab==='pending'?'待预约':'已预约及完成'} · 当前筛选结果`,columns:[{label:'日期 / 时间'},{label:'预约'},{label:'类型 / 状态'},{label:'城市 / 地点'},{label:'订单号'},{label:'预约链接'},{label:'备注'}],rows:items.map(item=>[`${item.date}${item.time?` ${item.time}`:''}`,item.name,`${item.type} · ${item.status}`,[item.city_id?cityById.get(item.city_id)?.name:'跨城市 / 未指定',item.location].filter(Boolean).join(' · ')||'—',item.order_number||'—',item.booking_url||'—',item.note||'—'])}
  return <div><PageHeader title="预约管理" description="跨城市的车票、酒店与活动预约，都按旅程顺序收好。" action="新增预约" onAction={()=>setEditing(null)}/><ErrorBanner message={error}/>
    <div className="control-panel mb-4 flex gap-2 overflow-x-auto !p-3"><button onClick={()=>setCityFilter(null)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${cityFilter===null?'bg-stone-900 text-white':'bg-white text-stone-500'}`}>全部城市</button>{data.cities.map(city=><button key={city.id} onClick={()=>setCityFilter(city.id)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${cityFilter===city.id?'bg-stone-900 text-white':'bg-white text-stone-500'}`}>{city.name}</button>)}</div>
    <div className="control-panel mb-4 flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div className="segmented-control inline-flex self-start rounded-2xl bg-white p-1 shadow-sm"><button onClick={()=>changeTab('booked')} className={`rounded-xl px-5 py-2 text-sm font-semibold transition ${tab==='booked'?'bg-coral-500 text-white shadow-md shadow-coral-500/20':'text-stone-500'}`}>已预约</button><button onClick={()=>changeTab('pending')} className={`rounded-xl px-5 py-2 text-sm font-semibold transition ${tab==='pending'?'bg-coral-500 text-white shadow-md shadow-coral-500/20':'text-stone-500'}`}>待预约</button></div><div className="flex flex-wrap gap-2">{types.map(type=><button key={type} onClick={()=>setFilter(type)} className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-semibold transition ${filter===type?'bg-stone-800 text-white shadow-md':'bg-white text-stone-500'}`}>{type!=='全部'&&<ReservationTypeIcon type={type} size={13}/>} {type}</button>)}</div><label className="relative block xl:w-72"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" size={16}/><input aria-label="搜索预约" className="w-full rounded-xl border border-stone-200 bg-white py-2.5 pl-10 pr-3 text-sm outline-none transition focus:border-coral-400" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索名称、订单号或地点"/></label></div>
    <DocumentExportActions table={exportTable}/>
    {!items.length?<EmptyState title={query?'没有找到匹配预约':'这里还没有预约'} message={query?'换个关键词，或清空搜索后再试试。':'想到要订的跨城车票、酒店或门票，都可以先放在这里。'} action="新增预约" onAction={()=>setEditing(null)}/>:<div className="stagger-list grid gap-5 lg:grid-cols-2 2xl:grid-cols-3">{items.map(item=>{const pdfs=data.attachments.filter(file=>file.reservation_id===item.id);return <article id={`reservation-${item.id}`} key={item.id} className={`card reservation-card min-w-0 overflow-hidden transition ${params.get('id')===String(item.id)?'ring-2 ring-coral-500':''}`}><ImageCover src={item.image_url} label={cityById.get(item.city_id||0)?.name||item.type} icon={<ReservationTypeIcon type={item.type} size={25}/>} tone={coverTone[item.type]}/><div className="p-5"><div className="flex min-w-0 items-start justify-between gap-3"><div className="min-w-0 flex-1">{item.city_id&&<p className="mb-1 text-xs font-semibold text-coral-600">{cityById.get(item.city_id)?.name}</p>}<h3 className="break-words text-lg font-bold leading-7">{item.name}</h3></div><Badge tone={item.status==='已预约'?'mint':item.status==='待预约'?'coral':'stone'}>{item.status}</Badge></div><div className="mt-4 min-w-0 space-y-2 text-sm text-stone-500"><p className="flex items-center gap-2"><CalendarDays className="shrink-0" size={15}/>{formatDate(item.date)} {item.time?.slice(0,5)}</p>{item.location&&<p className="flex items-start gap-2 break-words"><MapPin className="mt-0.5 shrink-0" size={15}/>{item.location}</p>}{item.order_number&&<p className="break-all text-xs">预约号：{item.order_number}</p>}</div><div className="mt-5 flex flex-wrap items-center gap-x-4 gap-y-3">{item.booking_url&&<LinkButton href={item.booking_url}>{item.status==='待预约'?'去预约':'查看订单'}</LinkButton>}{item.map_url&&<MapButton target={{title:item.name,url:item.map_url,query:item.location}} onOpen={setMapTarget}/>}<button onClick={()=>setAttachmentReservation(item)} className="inline-flex items-center gap-1.5 whitespace-nowrap text-sm font-semibold text-coral-600"><Paperclip size={15}/>PDF 附件{pdfs.length?` (${pdfs.length})`:''}</button></div><div className="mt-5 flex min-h-10 items-center justify-between gap-2 border-t border-stone-100 pt-3">{item.status==='待预约'?<button onClick={()=>void mark(item)} className="inline-flex items-center gap-1.5 text-sm font-semibold text-mint-600"><CheckCircle2 size={16}/>标为已预约</button>:<span/>}<div className="flex shrink-0"><IconButton aria-label="编辑" onClick={()=>setEditing(item)}><Edit3 size={17}/></IconButton><IconButton aria-label="删除" onClick={()=>void remove(item)}><Trash2 size={17}/></IconButton></div></div></div></article>})}</div>}
    <Modal open={editing!==undefined} title={editing?'编辑预约':'新增预约'} onClose={()=>setEditing(undefined)}><ReservationForm key={editing?.id||'new'} item={editing} cities={data.cities} tripId={tripId} onSave={save} onCancel={()=>setEditing(undefined)}/></Modal><Modal open={Boolean(attachmentReservation)} title={`${attachmentReservation?.name||''} · PDF 附件`} onClose={()=>setAttachmentReservation(null)}>{attachmentReservation&&<AttachmentManager reservation={attachmentReservation} attachments={data.attachments.filter(file=>file.reservation_id===attachmentReservation.id)} onChanged={reload}/>}</Modal><MapPreview target={mapTarget} onClose={()=>setMapTarget(null)}/>
  </div>
}

function AttachmentManager({reservation,attachments,onChanged}:{reservation:Reservation;attachments:ReservationAttachment[];onChanged:()=>Promise<void>}){
  const [uploading,setUploading]=useState(false),[error,setError]=useState('')
  const upload=async(file?:File)=>{if(!file)return;if(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){setError('请选择 PDF 文件');return}if(file.size>15*1024*1024){setError('PDF 文件不能超过 15 MB');return}setUploading(true);setError('');try{await api.reservationAttachments.upload(reservation.id,file);await onChanged()}catch(error){setError(error instanceof Error?error.message:'上传失败')}finally{setUploading(false)}}
  const remove=async(file:ReservationAttachment)=>{if(!confirm(`确定删除“${file.original_name}”吗？`))return;try{await api.reservationAttachments.remove(file.id);await onChanged()}catch(error){setError(error instanceof Error?error.message:'删除失败')}}
  const open=async(file:ReservationAttachment)=>{try{setError('');await api.reservationAttachments.open(file.id)}catch(error){setError(error instanceof Error?error.message:'无法打开附件')}}
  return <div><label className={`flex cursor-pointer items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-coral-200 bg-coral-50 px-5 py-8 text-sm font-semibold text-coral-700 transition hover:border-coral-400 ${uploading?'pointer-events-none opacity-60':''}`}><Upload size={20}/>{uploading?'正在上传并校验…':'选择车票、门票或确认单 PDF'}<input className="hidden" type="file" accept="application/pdf,.pdf" onChange={event=>void upload(event.target.files?.[0])}/></label><p className="mt-2 text-center text-xs text-stone-400">仅支持有效 PDF，单个文件最大 15 MB</p>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-600">{error}</p>}<div className="mt-5 space-y-3">{attachments.length?attachments.map(file=><div key={file.id} className="flex items-center gap-3 rounded-2xl border border-stone-100 p-4"><span className="rounded-xl bg-skysoft-50 p-2.5 text-skysoft-500"><FileText size={20}/></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.original_name}</p><p className="mt-1 text-xs text-stone-400">{(file.size_bytes/1024).toFixed(file.size_bytes>1024*1024?0:1)} KB · {new Date(file.uploaded_at).toLocaleString('zh-CN')}</p></div><button type="button" className="secondary-btn" onClick={()=>void open(file)}>查看</button><IconButton aria-label="删除附件" onClick={()=>void remove(file)}><Trash2 size={17}/></IconButton></div>):<p className="py-5 text-center text-sm text-stone-400">还没有上传 PDF 附件。</p>}</div></div>
}
