import { useState, type FormEvent } from 'react'
import { MapPin, Search } from 'lucide-react'
import { api } from '../api/client'
import { currencies } from '../data/currencies'
import { fetchExchangeRateToCny } from '../utils/exchangeRates'
import type { City, Destination, Expense, GeocodeResult, Inspiration, ItineraryItem, NewItem, Place, Reservation, RouteLeg, TransportMode, Trip } from '../types'
import { ErrorBanner, FormActions, FormInput, FormSelect, FormTextarea } from './UI'

const today = () => new Date().toISOString().slice(0, 10)
const opts = (values: readonly string[]) => values.map(x => <option key={x}>{x}</option>)
type SaveProps<T extends { id: number }> = { item?: T | null; onSave: (data: NewItem<T>) => Promise<void>; onCancel: () => void }
const numberOrNull=(value:string)=>value.trim()===''?null:Number(value)

function FormShell({ children, onSubmit, saving, error, onCancel }: { children: React.ReactNode; onSubmit: (e: FormEvent) => void; saving: boolean; error: string; onCancel: () => void }) {
  return <form onSubmit={onSubmit}><ErrorBanner message={error}/><div className="grid gap-4 sm:grid-cols-2">{children}</div><FormActions saving={saving} onCancel={onCancel}/></form>
}

function useSubmit<T>(action: (data: T) => Promise<void>) {
  const [saving,setSaving]=useState(false); const [error,setError]=useState('')
  const submit=async(data:T)=>{setSaving(true);setError('');try{await action(data)}catch(e){setError(e instanceof Error?e.message:'保存失败')}finally{setSaving(false)}}
  return {saving,error,submit}
}

function LocationSearch({initialValue='',onSelect}:{initialValue?:string;onSelect:(result:GeocodeResult)=>void}){
  const [query,setQuery]=useState(initialValue),[results,setResults]=useState<GeocodeResult[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState('')
  const search=async()=>{if(query.trim().length<2){setError('请至少输入两个字符');return}setLoading(true);setError('');try{setResults(await api.geocode.search(query.trim()))}catch(e){setError(e instanceof Error?e.message:'地点搜索失败')}finally{setLoading(false)}}
  return <div className="sm:col-span-2 rounded-2xl border border-sky-100 bg-skysoft-50/50 p-4"><p className="flex items-center gap-2 text-sm font-semibold text-stone-700"><MapPin size={16} className="text-coral-500"/>搜索地点并选择坐标</p><div className="mt-3 flex gap-2"><input className="min-w-0 flex-1 rounded-xl border border-stone-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-coral-500" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search()}}} placeholder="输入中英文地名或地址"/><button type="button" className="secondary-btn shrink-0" disabled={loading} onClick={()=>void search()}><Search size={16}/>{loading?'搜索中':'搜索'}</button></div>{error&&<p className="mt-2 text-xs text-red-600">{error}</p>}{results.length>0&&<div className="mt-3 space-y-2">{results.map((result,index)=><button type="button" key={`${result.latitude}-${result.longitude}-${index}`} onClick={()=>{onSelect(result);setResults([]);setQuery(result.name)}} className="block w-full rounded-xl border border-stone-100 bg-white p-3 text-left transition hover:border-coral-300"><b className="block text-sm">{result.name}</b><span className="mt-1 block text-xs leading-5 text-stone-400">{result.display_name}</span></button>)}</div>}<p className="mt-2 text-xs text-stone-400">选择结果后会自动填入名称、地址和经纬度；也可以不搜索直接保存。</p></div>
}

export function ItineraryForm({ item, onSave, onCancel, reservations, inspirations, places, cities, tripId }: SaveProps<ItineraryItem> & { reservations: Reservation[]; inspirations: Inspiration[]; places: Place[]; cities: City[]; tripId: number }) {
  const initialReservationIds=[...(item?.reservation_ids||[]),item?.reservation_id].filter((id):id is number=>Boolean(id)).filter((id,index,all)=>all.indexOf(id)===index)
  const [data,setData]=useState<NewItem<ItineraryItem>>(item ? { ...item,reservation_ids:initialReservationIds,reservation_id:initialReservationIds[0]||null,inspiration_id:item.inspiration_id??null } : { trip_id:tripId,title:'',date:today(),start_time:'09:00',end_time:null,type:'景点',location:null,note:'',reservation_id:null,reservation_ids:[],inspiration_id:null,place_id:null,map_url:'',image_url:null,city_id:cities[0]?.id||null })
  const s=useSubmit(onSave); const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  const toggleReservation=(id:number)=>setData(value=>{const current=value.reservation_ids||[];const reservation_ids=current.includes(id)?current.filter(itemId=>itemId!==id):[...current,id];return {...value,reservation_ids,reservation_id:reservation_ids[0]||null}})
  return <FormShell onSubmit={e=>{e.preventDefault();const reservation_ids=data.reservation_ids||[];void s.submit({...data,end_time:data.end_time||null,location:null,note:data.note||null,reservation_id:reservation_ids[0]||null,reservation_ids,map_url:data.map_url||null,image_url:null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <div className="sm:col-span-2"><FormInput required label="标题" placeholder="例如：清水寺晨间参观" value={data.title} onChange={e=>change('title',e.target.value)}/></div>
    <FormInput required type="date" label="日期" value={data.date} onChange={e=>change('date',e.target.value)}/><FormSelect label="城市" value={data.city_id??''} onChange={e=>change('city_id',e.target.value?Number(e.target.value):null)}><option value="">跨城市 / 未指定</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</FormSelect><FormSelect label="类型" value={data.type} onChange={e=>change('type',e.target.value)}>{opts(['交通','酒店','景点','餐饮','购物','其他'])}</FormSelect>
    <FormInput required type="time" label="开始时间" value={data.start_time.slice(0,5)} onChange={e=>change('start_time',e.target.value)}/><FormInput type="time" label="结束时间" value={data.end_time?.slice(0,5)||''} onChange={e=>change('end_time',e.target.value||null)}/>
    <FormSelect label="关联地点" value={data.place_id??''} onChange={e=>change('place_id',e.target.value?Number(e.target.value):null)}><option value="">不关联</option>{places.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</FormSelect>
    <FormSelect label="关联灵感帖子" value={data.inspiration_id??''} onChange={e=>change('inspiration_id',e.target.value?Number(e.target.value):null)}><option value="">不关联</option>{inspirations.map(inspiration=><option key={inspiration.id} value={inspiration.id}>{inspiration.platform} · {inspiration.title}</option>)}</FormSelect>
    <FormInput type="url" label="地图链接（可选）" placeholder="https://…" value={data.map_url||''} onChange={e=>change('map_url',e.target.value)}/>
    <fieldset className="sm:col-span-2 rounded-2xl border border-mint-100 bg-mint-50/60 p-4"><legend className="px-1 text-sm font-semibold text-stone-700">关联预约（可多选）</legend><p className="mb-3 text-xs leading-5 text-stone-500">日程不单独保存附件；关联后可从日程直接打开每个预约中的 PDF 文件。</p>{reservations.length?<div className="grid gap-2 sm:grid-cols-2">{reservations.map(reservation=><label key={reservation.id} className={`flex cursor-pointer items-center gap-3 rounded-xl border px-3 py-2.5 text-sm transition ${(data.reservation_ids||[]).includes(reservation.id)?'border-mint-300 bg-white text-stone-800':'border-white bg-white/65 text-stone-500'}`}><input type="checkbox" className="h-4 w-4 accent-mint-500" checked={(data.reservation_ids||[]).includes(reservation.id)} onChange={()=>toggleReservation(reservation.id)}/><span className="min-w-0"><b className="block truncate">{reservation.name}</b><small className="block text-xs text-stone-400">{reservation.type} · {reservation.date}</small></span></label>)}</div>:<p className="text-sm text-stone-400">还没有可关联的预约，先到“预约”页面添加即可。</p>}</fieldset>
    <div className="sm:col-span-2"><FormTextarea label="备注" placeholder="交通、集合点或其他提醒" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export function ReservationForm({ item, onSave, onCancel, cities, tripId }: SaveProps<Reservation> & { cities: City[]; tripId: number }) {
  const [data,setData]=useState<NewItem<Reservation>>(item ? { ...item } : {trip_id:tripId,name:'',type:'景点',date:today(),time:null,status:'待预约',order_number:'',location:'',note:'',booking_url:'',map_url:'',image_url:'',city_id:cities[0]?.id||null})
  const s=useSubmit(onSave); const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,time:data.time||null,order_number:data.order_number||null,location:data.location||null,note:data.note||null,booking_url:data.booking_url||null,map_url:data.map_url||null,image_url:data.image_url||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <div className="sm:col-span-2"><FormInput required label="名称" placeholder="例如：岚山嵯峨野小火车" value={data.name} onChange={e=>change('name',e.target.value)}/></div>
    <FormSelect label="城市" value={data.city_id??''} onChange={e=>change('city_id',e.target.value?Number(e.target.value):null)}><option value="">跨城市 / 未指定</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</FormSelect><FormSelect label="类型" value={data.type} onChange={e=>change('type',e.target.value)}>{opts(['酒店','车票','机票','景点','餐厅','其他'])}</FormSelect><FormSelect label="状态" value={data.status} onChange={e=>change('status',e.target.value)}>{opts(['已预约','待预约','已完成','已取消'])}</FormSelect>
    <FormInput required type="date" label="日期" value={data.date} onChange={e=>change('date',e.target.value)}/><FormInput type="time" label="时间" value={data.time?.slice(0,5)||''} onChange={e=>change('time',e.target.value||null)}/>
    <FormInput label="预约号 / 订单号" placeholder="可选" value={data.order_number||''} onChange={e=>change('order_number',e.target.value)}/><FormInput label="地点" placeholder="集合地点" value={data.location||''} onChange={e=>change('location',e.target.value)}/>
    <FormInput type="url" label="预约链接" placeholder="https://…" value={data.booking_url||''} onChange={e=>change('booking_url',e.target.value)}/><FormInput type="url" label="地图链接" placeholder="https://…" value={data.map_url||''} onChange={e=>change('map_url',e.target.value)}/>
    <div className="sm:col-span-2"><FormInput type="url" label="图片链接" placeholder="https://…" value={data.image_url||''} onChange={e=>change('image_url',e.target.value)}/></div><div className="sm:col-span-2"><FormTextarea label="备注" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export function InspirationForm({ item, onSave, onCancel, tripId }: SaveProps<Inspiration> & { tripId: number }) {
  const [data,setData]=useState<NewItem<Inspiration>>(item ? { ...item } : {trip_id:tripId,title:'',platform:'小红书',url:'',tags:[],related_place:'',note:'',image_url:'',favorite:true})
  const [tags,setTags]=useState(data.tags.join('，')); const s=useSubmit(onSave); const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,tags:tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean),related_place:data.related_place||null,note:data.note||null,image_url:data.image_url||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <div className="sm:col-span-2"><FormInput required label="标题" placeholder="这篇攻略讲了什么？" value={data.title} onChange={e=>change('title',e.target.value)}/></div>
    <FormSelect label="平台" value={data.platform} onChange={e=>change('platform',e.target.value)}>{opts(['小红书','公众号','网页','其他'])}</FormSelect><FormInput label="关联地点" placeholder="例如：祇园" value={data.related_place||''} onChange={e=>change('related_place',e.target.value)}/>
    <div className="sm:col-span-2"><FormInput required type="url" label="攻略链接" placeholder="https://…" value={data.url} onChange={e=>change('url',e.target.value)}/></div>
    <FormInput label="标签" placeholder="美食，拍照，小众" value={tags} onChange={e=>setTags(e.target.value)}/><FormInput type="url" label="封面图片链接" placeholder="https://…" value={data.image_url||''} onChange={e=>change('image_url',e.target.value)}/>
    <label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" className="h-4 w-4 accent-coral-500" checked={data.favorite} onChange={e=>change('favorite',e.target.checked)}/>加入收藏</label><div/>
    <div className="sm:col-span-2"><FormTextarea label="备注" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export function PlaceForm({ item, onSave, onCancel, cities, tripId }: SaveProps<Place> & { cities: City[]; tripId: number }) {
  const initialCity=cities.find(x=>x.id===item?.city_id)||cities[0];
  const [data,setData]=useState<NewItem<Place>>(item ? { ...item } : {trip_id:tripId,name:'',type:'景点',city:initialCity?.name||'',address:'',map_url:'',note:'',image_url:'',city_id:initialCity?.id||null,latitude:null,longitude:null}); const s=useSubmit(onSave); const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,city:data.city||null,address:data.address||null,map_url:data.map_url||null,note:data.note||null,image_url:data.image_url||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <LocationSearch initialValue={[data.name,data.city].filter(Boolean).join(' ')} onSelect={result=>setData(v=>({...v,name:result.name,address:result.display_name,latitude:result.latitude,longitude:result.longitude,map_url:`https://www.openstreetmap.org/?mlat=${result.latitude}&mlon=${result.longitude}#map=16/${result.latitude}/${result.longitude}`}))}/>
    <div className="sm:col-span-2"><FormInput required label="地点名称" placeholder="例如：浅草寺" value={data.name} onChange={e=>change('name',e.target.value)}/></div><FormSelect label="类型" value={data.type} onChange={e=>change('type',e.target.value)}>{opts(['酒店','车站','机场','景点','餐厅','商场','其他'])}</FormSelect><FormSelect label="所属城市" value={data.city_id??''} onChange={e=>{const id=e.target.value?Number(e.target.value):null;const city=cities.find(x=>x.id===id);setData(v=>({...v,city_id:id,city:city?.name||''}))}}><option value="">未指定</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</FormSelect>
    <div className="sm:col-span-2"><FormInput label="地址" placeholder="详细地址" value={data.address||''} onChange={e=>change('address',e.target.value)}/></div><details className="sm:col-span-2 rounded-xl border border-stone-100 p-3"><summary className="cursor-pointer text-sm font-medium text-stone-500">手动修改坐标（可选）</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><FormInput type="number" step="0.000001" min="-90" max="90" label="纬度" value={data.latitude??''} onChange={e=>change('latitude',e.target.value?Number(e.target.value):null)}/><FormInput type="number" step="0.000001" min="-180" max="180" label="经度" value={data.longitude??''} onChange={e=>change('longitude',e.target.value?Number(e.target.value):null)}/></div></details><FormInput type="url" label="地图链接" placeholder="https://…" value={data.map_url||''} onChange={e=>change('map_url',e.target.value)}/><FormInput type="url" label="图片链接" placeholder="https://…" value={data.image_url||''} onChange={e=>change('image_url',e.target.value)}/><div className="sm:col-span-2"><FormTextarea label="备注" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export function CityForm({ item, onSave, onCancel, tripId, destinations }: SaveProps<City> & { tripId:number; destinations:Destination[] }) {
  const initialDestination=destinations.find(x=>x.id===item?.destination_id)||destinations[0]
  const [data,setData]=useState<NewItem<City>>(item?{...item}:{trip_id:tripId,destination_id:initialDestination?.id||null,name:'',country:initialDestination?.name||'',order_index:0,arrival_date:null,departure_date:null,latitude:null,longitude:null,note:''});const s=useSubmit(onSave);const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,country:data.country||null,arrival_date:data.arrival_date||null,departure_date:data.departure_date||null,note:data.note||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <LocationSearch initialValue={[data.name,data.country].filter(Boolean).join(' ')} onSelect={result=>setData(v=>({...v,name:result.name,latitude:result.latitude,longitude:result.longitude}))}/><FormInput required label="城市名称" placeholder="例如：巴黎" value={data.name} onChange={e=>change('name',e.target.value)}/><FormSelect required label="所属国家 / 地区" value={data.destination_id??''} onChange={e=>{const id=Number(e.target.value);const destination=destinations.find(x=>x.id===id);setData(v=>({...v,destination_id:id,country:destination?.name||''}))}}><option value="">请选择</option>{destinations.map(x=><option key={x.id} value={x.id}>{x.type} · {x.name}</option>)}</FormSelect><FormInput type="date" label="抵达日期" value={data.arrival_date||''} onChange={e=>change('arrival_date',e.target.value||null)}/><FormInput type="date" label="离开日期" value={data.departure_date||''} onChange={e=>change('departure_date',e.target.value||null)}/><details className="sm:col-span-2 rounded-xl border border-stone-100 p-3"><summary className="cursor-pointer text-sm font-medium text-stone-500">手动修改坐标（可选）</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><FormInput type="number" step="0.000001" min="-90" max="90" label="纬度" value={data.latitude??''} onChange={e=>change('latitude',e.target.value?Number(e.target.value):null)}/><FormInput type="number" step="0.000001" min="-180" max="180" label="经度" value={data.longitude??''} onChange={e=>change('longitude',e.target.value?Number(e.target.value):null)}/></div></details><div className="sm:col-span-2"><FormTextarea label="城市备注" placeholder="本城的旅行重点" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

const TRANSPORT_MODES:TransportMode[]=['步行','公共交通','出租车','自驾','骑行','火车','大巴','飞机','轮渡','其他']
export function RouteLegForm({ item, onSave, onCancel, places, reservations, tripId }: SaveProps<RouteLeg> & { places: Place[]; reservations: Reservation[]; tripId:number }) {
  const [data,setData]=useState<NewItem<RouteLeg>>(item?{...item}:{trip_id:tripId,title:'',from_place_id:places[0]?.id||0,to_place_id:places[1]?.id||0,transport_modes:['步行','公共交通'],selected_mode:'公共交通',duration_minutes:null,reservation_id:null,order_index:0,note:''});const [durationInput,setDurationInput]=useState(item?.duration_minutes==null?'':String(item.duration_minutes));const [orderInput,setOrderInput]=useState(String(item?.order_index??0));const s=useSubmit(onSave);const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}));const toggle=(mode:TransportMode)=>setData(v=>{const modes=v.transport_modes.includes(mode)?v.transport_modes.filter(x=>x!==mode):[...v.transport_modes,mode];return {...v,transport_modes:modes,selected_mode:v.selected_mode&&modes.includes(v.selected_mode)?v.selected_mode:(modes[0]||null)}})
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,duration_minutes:data.duration_minutes||null,reservation_id:data.reservation_id||null,note:data.note||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <div className="sm:col-span-2"><FormInput required label="路线名称" placeholder="例如：京都 → 东京" value={data.title} onChange={e=>change('title',e.target.value)}/></div><FormSelect required label="起点" value={data.from_place_id} onChange={e=>change('from_place_id',Number(e.target.value))}>{places.map(x=><option key={x.id} value={x.id}>{x.city} · {x.name}</option>)}</FormSelect><FormSelect required label="终点" value={data.to_place_id} onChange={e=>change('to_place_id',Number(e.target.value))}>{places.map(x=><option key={x.id} value={x.id}>{x.city} · {x.name}</option>)}</FormSelect><div className="sm:col-span-2"><p className="text-sm font-medium text-stone-700">可选交通方式</p><div className="mt-2 flex flex-wrap gap-2">{TRANSPORT_MODES.map(mode=><label key={mode} className={`cursor-pointer rounded-full border px-3 py-2 text-xs font-semibold ${data.transport_modes.includes(mode)?'border-coral-500 bg-coral-50 text-coral-700':'border-stone-200 text-stone-500'}`}><input type="checkbox" className="sr-only" checked={data.transport_modes.includes(mode)} onChange={()=>toggle(mode)}/>{mode}</label>)}</div></div><FormSelect label="当前选择" value={data.selected_mode||''} onChange={e=>change('selected_mode',e.target.value||null)}><option value="">暂未决定</option>{data.transport_modes.map(x=><option key={x}>{x}</option>)}</FormSelect><FormInput type="number" min="1" label="预计分钟" value={durationInput} onChange={e=>{setDurationInput(e.target.value);change('duration_minutes',numberOrNull(e.target.value))}}/><FormSelect label="关联交通预约" value={data.reservation_id??''} onChange={e=>change('reservation_id',e.target.value?Number(e.target.value):null)}><option value="">不关联</option>{reservations.filter(x=>['车票','机票','其他'].includes(x.type)).map(x=><option key={x.id} value={x.id}>{x.type} · {x.name}</option>)}</FormSelect><FormInput required type="number" min="0" label="路线顺序" value={orderInput} onChange={e=>{setOrderInput(e.target.value);change('order_index',numberOrNull(e.target.value)||0)}}/><div className="sm:col-span-2"><FormTextarea label="路线备注" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export function ExpenseForm({ item, onSave, onCancel, itinerary, reservations, tripCurrency, tripId }: SaveProps<Expense> & { itinerary: ItineraryItem[]; reservations: Reservation[]; tripCurrency: string; tripId:number }) {
  const [data,setData]=useState<NewItem<Expense>>(item ? { ...item } : {trip_id:tripId,title:'',amount:0,currency:'CNY',original_amount:null,original_currency:'CNY',exchange_rate:1,date:today(),category:'餐饮',payment_method:'',note:'',is_split:false,itinerary_id:null,reservation_id:null})
  const [originalInput,setOriginalInput]=useState(item?String(item.original_amount??item.amount):'')
  const [rateInput,setRateInput]=useState(item?String(item.exchange_rate??1):'1')
  const [convertedInput,setConvertedInput]=useState(item?String(item.amount):'')
  const [rateMessage,setRateMessage]=useState('')
  const s=useSubmit(onSave); const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}));const recalculate=(amount:number,rate:number)=>Number((amount*rate).toFixed(2))
  const setCalculatedAmount=(original:string,rate:string)=>{const amount=numberOrNull(original),exchangeRate=numberOrNull(rate);if(amount===null||exchangeRate===null)return;const converted=recalculate(amount,exchangeRate);setConvertedInput(String(converted));setData(value=>({...value,amount:converted}))}
  const onOriginalChange=(value:string)=>{setOriginalInput(value);setData(current=>({...current,original_amount:numberOrNull(value)}));setCalculatedAmount(value,rateInput)}
  const onRateChange=(value:string)=>{setRateInput(value);setData(current=>({...current,exchange_rate:numberOrNull(value)}));setCalculatedAmount(originalInput,value)}
  const applyCurrency=async(currency:string)=>{setData(value=>({...value,original_currency:currency}));if(currency==='CNY'){setRateMessage('人民币无需换算，汇率已设为 1。');onRateChange('1');return}setRateMessage('正在自动获取最新汇率…');try{const result=await fetchExchangeRateToCny(currency);onRateChange(String(result.rate));setRateMessage(result.source==='live'?`已自动填充 ${result.date||'最新'} 汇率：1 ${currency} = ${result.rate} CNY`:`网络不可用或接口暂不支持，已使用本地兜底汇率：1 ${currency} ≈ ${result.rate} CNY`)}catch(error){setRateMessage(error instanceof Error?error.message:'暂时无法获取汇率，可手动填写。')}}
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,currency:'CNY',original_amount:data.original_amount||null,original_currency:data.original_currency||null,exchange_rate:data.exchange_rate||null,payment_method:data.payment_method||null,note:data.note||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <div className="sm:col-span-2"><FormInput required label="消费项目" placeholder="例如：拉面午餐" value={data.title} onChange={e=>change('title',e.target.value)}/></div><FormInput required min="0.01" step="0.01" type="number" label="原币金额" value={originalInput} onChange={e=>onOriginalChange(e.target.value)}/><FormSelect label="原币币种" value={data.original_currency||'CNY'} onChange={e=>void applyCurrency(e.target.value)}>{currencyOptions}</FormSelect>{rateMessage&&<p className="sm:col-span-2 rounded-xl bg-skysoft-50 px-3 py-2 text-xs font-semibold leading-5 text-sky-700">{rateMessage}</p>}<FormInput required min="0.000001" step="0.000001" type="number" label="汇率（1 原币 = CNY）" value={rateInput} onChange={e=>{setRateMessage('已手动修改汇率。');onRateChange(e.target.value)}}/><FormInput required min="0.01" step="0.01" type="number" label="折合人民币" value={convertedInput} onChange={e=>{setConvertedInput(e.target.value);change('amount',numberOrNull(e.target.value)||0)}}/>
    <FormInput required type="date" label="日期" value={data.date} onChange={e=>change('date',e.target.value)}/>
    <FormSelect label="分类" value={data.category} onChange={e=>change('category',e.target.value)}>{opts(['交通','住宿','餐饮','门票','购物','其他'])}</FormSelect><FormInput label="支付方式" placeholder="微信 / 信用卡 / 现金" value={data.payment_method||''} onChange={e=>change('payment_method',e.target.value)}/>
    <FormSelect label="关联日程" value={data.itinerary_id??''} onChange={e=>change('itinerary_id',e.target.value?Number(e.target.value):null)}><option value="">不关联</option>{itinerary.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</FormSelect><FormSelect label="关联预约" value={data.reservation_id??''} onChange={e=>change('reservation_id',e.target.value?Number(e.target.value):null)}><option value="">不关联</option>{reservations.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</FormSelect>
    <p className="sm:col-span-2 rounded-xl bg-stone-50 px-3 py-2 text-xs leading-5 text-stone-500">关联日程用于把消费归到某一项活动；关联预约用于把订票、酒店或门票支出归到对应订单。它们会显示在消费记录与导出文件中，方便回溯，不会改变预算计算。</p>
    <label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" className="h-4 w-4 accent-coral-500" checked={data.is_split} onChange={e=>change('is_split',e.target.checked)}/>这笔消费需要 AA</label><div/><div className="sm:col-span-2"><FormTextarea label="备注" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export function TripForm({ item, onSave, onCancel }: SaveProps<Trip>) {
  const start=new Date();start.setDate(start.getDate()+30);const end=new Date(start);end.setDate(end.getDate()+6)
  const [data,setData]=useState<NewItem<Trip>>(item?{...item}:{name:'',start_date:start.toISOString().slice(0,10),end_date:end.toISOString().slice(0,10),total_budget:0,currency:'CNY'});const [budgetInput,setBudgetInput]=useState(item?String(item.total_budget):'');const s=useSubmit(onSave);const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit(data)}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <div className="sm:col-span-2"><FormInput required label="旅程名称" placeholder="例如：法国与英国 12 日游" value={data.name} onChange={e=>change('name',e.target.value)}/></div><FormInput required type="date" label="开始日期" value={data.start_date} onChange={e=>change('start_date',e.target.value)}/><FormInput required type="date" label="结束日期" value={data.end_date} onChange={e=>change('end_date',e.target.value)}/><FormInput required type="number" min="0" step="0.01" label="总预算" value={budgetInput} onChange={e=>{setBudgetInput(e.target.value);change('total_budget',numberOrNull(e.target.value)||0)}}/><FormSelect label="预算货币" value={data.currency} onChange={e=>change('currency',e.target.value)}>{currencyOptions}</FormSelect>
  </FormShell>
}

export function DestinationForm({ item, onSave, onCancel, tripId, destinations }: SaveProps<Destination> & { tripId:number; destinations:Destination[] }) {
  const [data,setData]=useState<NewItem<Destination>>(item?{...item}:{trip_id:tripId,name:'',type:'国家',code:'',order_index:destinations.length,parent_id:null,note:''});const [orderInput,setOrderInput]=useState(String(item?.order_index??destinations.length));const s=useSubmit(onSave);const change=(key:keyof typeof data,value:unknown)=>setData(v=>({...v,[key]:value}))
  return <FormShell onSubmit={e=>{e.preventDefault();void s.submit({...data,code:data.code||null,parent_id:data.parent_id||null,note:data.note||null})}} saving={s.saving} error={s.error} onCancel={onCancel}>
    <FormInput required label="国家 / 地区名称" placeholder="例如：法国、关西地区" value={data.name} onChange={e=>change('name',e.target.value)}/><FormSelect label="类型" value={data.type} onChange={e=>change('type',e.target.value)}><option>国家</option><option>地区</option></FormSelect><FormInput label="代码" placeholder="例如 FR、JP" maxLength={10} value={data.code||''} onChange={e=>change('code',e.target.value.toUpperCase())}/><FormInput required type="number" min="0" label="旅程顺序" value={orderInput} onChange={e=>{setOrderInput(e.target.value);change('order_index',numberOrNull(e.target.value)||0)}}/>{data.type==='地区'&&<div className="sm:col-span-2"><FormSelect label="所属国家（可选）" value={data.parent_id??''} onChange={e=>change('parent_id',e.target.value?Number(e.target.value):null)}><option value="">无上级</option>{destinations.filter(x=>x.type==='国家'&&x.id!==item?.id).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</FormSelect></div>}<div className="sm:col-span-2"><FormTextarea label="备注" placeholder="签证、语言或本段旅行重点" value={data.note||''} onChange={e=>change('note',e.target.value)}/></div>
  </FormShell>
}

export const currencyOptions = <>{currencies.map(([value,label])=><option key={value} value={value}>{label} {value}</option>)}</>
