import { ArrowRight, Building2, CalendarCheck, CalendarClock, CircleDollarSign, Clock3, Globe2, Lightbulb, MapPin, NotebookTabs, Plus, ReceiptText } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import { Badge, EmptyState, ErrorBanner, LinkButton, Loading, ReservationTypeIcon, StatCard } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import { useTrip } from '../contexts/TripContext'
import { formatDate, formatMoney, tripStatus } from '../utils'

export default function Dashboard() {
  const {selectedTrip}=useTrip();const trip=selectedTrip!;const tripId=trip.id
  const {data,loading,error}=useLoad(async()=>{const [destinations,cities,itinerary,reservations,inspirations,expenses]=await Promise.all([api.destinations.list({trip_id:tripId}),api.cities.list({trip_id:tripId}),api.itinerary.list({trip_id:tripId}),api.reservations.list({trip_id:tripId}),api.inspirations.list({trip_id:tripId}),api.expenses.list({trip_id:tripId})]);return {destinations,cities,itinerary,reservations,inspirations,expenses}})
  if(loading)return <Loading/>; if(!data)return <ErrorBanner message={error}/>
  const {destinations,cities,itinerary,reservations,inspirations,expenses}=data
  const baseExpenses=expenses, foreignExpenses=0
  const spent=baseExpenses.reduce((s,x)=>s+Number(x.amount),0), percent=trip.total_budget?Math.min(100,spent/Number(trip.total_budget)*100):0
  const today=new Date().toISOString().slice(0,10), upcoming=itinerary.find(x=>x.date>=today)
  const todayItems=itinerary.filter(x=>x.date===today), pending=reservations.filter(x=>x.status==='待预约'), booked=reservations.filter(x=>x.status==='已预约')
  const favorite=inspirations.filter(x=>x.favorite).slice(0,3), status=tripStatus(trip.start_date,trip.end_date)
  const quick=[['/itinerary?new=1','新增日程',CalendarCheck],['/reservations?new=1','新增预约',NotebookTabs],['/inspirations?new=1','新增灵感',Lightbulb],['/expenses?new=1','记一笔',ReceiptText]] as const
  const upcomingLink=upcoming?.city_id?`/itinerary?city_id=${upcoming.city_id}`:'/itinerary'
  return <div className="min-w-0 max-w-full overflow-x-clip">
    <ErrorBanner message={error}/>
    <section className="relative overflow-hidden rounded-4xl border border-white/10 bg-[#292824] p-7 text-white shadow-[0_28px_70px_-26px_rgba(41,40,36,.65)] sm:p-9">
      <div className="absolute inset-0 opacity-[.055]" style={{backgroundImage:'linear-gradient(rgba(255,255,255,.8) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.8) 1px,transparent 1px)',backgroundSize:'34px 34px'}}/><div className="absolute -right-16 -top-24 h-64 w-64 rounded-full bg-coral-500/25 blur-3xl"/><div className="absolute -bottom-20 right-32 h-48 w-48 rounded-full bg-mint-500/20 blur-3xl"/>
      <div className="relative"><p className="text-sm font-semibold uppercase tracking-[.25em] text-coral-500">Next journey</p><div className="mt-3 flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between lg:gap-10"><div className="min-w-0 flex-1"><h1 className="text-3xl font-extrabold tracking-[-.03em] sm:text-4xl">{trip!.name}</h1><p className="mt-3 flex items-center gap-2 text-stone-300"><CalendarClock size={18}/>{formatDate(trip!.start_date,{year:'numeric',month:'long',day:'numeric'})} — {formatDate(trip!.end_date,{year:'numeric',month:'long',day:'numeric'})}</p><div className="mt-5 space-y-4"><div className="flex items-start gap-3"><span className="mt-0.5 rounded-lg bg-white/10 p-1.5 text-stone-300"><Globe2 size={15}/></span><div className="min-w-0"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-stone-400">国家 / 地区</p><div className="flex flex-wrap gap-2">{destinations.map(destination=><span key={destination.id} className="rounded-full border border-white/10 bg-white/[.07] px-3 py-1.5 text-xs font-semibold text-stone-200 backdrop-blur">{destination.name}</span>)}</div></div></div><div className="flex items-start gap-3 border-t border-white/10 pt-4"><span className="mt-0.5 rounded-lg bg-mint-500/15 p-1.5 text-mint-100"><Building2 size={15}/></span><div className="min-w-0 flex-1"><p className="mb-2 text-[10px] font-bold uppercase tracking-[.18em] text-mint-100/60">城市日程 · 点击查看</p><div className="flex gap-2 overflow-x-auto pb-2">{cities.map(city=><Link key={city.id} to={`/itinerary?city_id=${city.id}`} aria-label={`查看${city.name}日程`} className="group inline-flex shrink-0 items-center gap-1.5 rounded-full border border-mint-500/20 bg-mint-500/10 px-3 py-1.5 text-xs font-semibold text-mint-100 backdrop-blur transition hover:-translate-y-0.5 hover:border-mint-500/50 hover:bg-mint-500/20">{city.name}<ArrowRight className="opacity-50 transition group-hover:translate-x-0.5 group-hover:opacity-100" size={12}/></Link>)}</div></div></div></div><p className="mt-2 text-lg font-semibold text-mint-500">{status.label}</p></div><div className="w-full max-w-sm rounded-3xl border border-white/10 bg-white/[.055] p-5 backdrop-blur-sm"><div className="mb-2 flex justify-between text-sm font-semibold"><span>预算使用</span><span>{percent.toFixed(0)}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-gradient-to-r from-coral-500 to-amber-300 shadow-[0_0_18px_rgba(255,190,90,.35)]" style={{width:`${percent}%`}}/></div><p className="mt-3 text-right text-xs text-stone-400">{formatMoney(spent,trip!.currency)} / {formatMoney(Number(trip!.total_budget),trip!.currency)}</p></div></div></div>
    </section>
    <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{quick.map(([to,label,Icon])=><Link key={to} to={to} className="card content-card interactive-card group flex items-center gap-3 p-4 text-sm font-semibold"><span className="rounded-xl bg-gradient-to-br from-coral-50 to-amber-50 p-2 text-coral-500 transition group-hover:scale-105 group-hover:bg-coral-500 group-hover:text-white"><Icon size={18}/></span>{label}<Plus className="ml-auto text-stone-300 transition group-hover:rotate-90 group-hover:text-coral-500" size={16}/></Link>)}</div>
    <div className="stagger-list mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard to={upcomingLink} label="下一项行程" value={upcoming?.title||'暂无安排'} note={upcoming?`${formatDate(upcoming.date)} ${upcoming.start_time.slice(0,5)}`:'去日程页添加吧'} icon={<Clock3/>}/><StatCard to="/reservations?tab=booked" label="已预约" value={`${booked.length} 项`} note="一切都在计划中" icon={<CalendarCheck/>}/><StatCard to="/reservations?tab=pending" label="待预约" value={`${pending.length} 项`} note={pending.length?'别忘了确认名额':'没有待办预约'} icon={<CalendarClock/>}/><StatCard to="/expenses" label="已支出" value={formatMoney(spent,trip.currency)} note={foreignExpenses?`另有 ${foreignExpenses} 笔外币支出未折算`:`剩余 ${formatMoney(Number(trip.total_budget)-spent,trip.currency)}`} icon={<CircleDollarSign/>}/></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-3">
      <section className="section-card section-coral p-6 xl:col-span-1"><div className="flex items-center justify-between"><h2 className="font-bold">今日日程</h2><Link to="/itinerary" className="text-xs font-semibold text-coral-600">全部日程</Link></div>{todayItems.length?<div className="mt-5 space-y-5 border-l-2 border-coral-100 pl-5">{todayItems.map(x=><Link to={x.city_id?`/itinerary?city_id=${x.city_id}`:'/itinerary'} key={x.id} className="pressable-card relative block rounded-xl p-1 transition hover:bg-coral-50"><span className="absolute -left-[27px] top-2 h-3 w-3 rounded-full bg-coral-500 ring-4 ring-white"/><p className="text-xs font-bold text-coral-600">{x.start_time.slice(0,5)}</p><p className="mt-1 font-semibold">{x.title}</p><p className="mt-1 flex items-center gap-1 text-xs text-stone-400"><MapPin size={12}/>{x.location||'地点待定'}</p></Link>)}</div>:<Link to="/itinerary" className="mt-6 block text-sm text-stone-400">今天没有安排，去日程页看看吧。</Link>}</section>
      <section className="dashboard-section section-card section-mint p-6"><div className="flex min-w-0 items-center justify-between gap-3"><h2 className="min-w-0 font-bold">待办预约</h2><Link to="/reservations?tab=pending" className="shrink-0 text-xs font-semibold text-coral-600">查看全部</Link></div>{pending.length?<div className="mt-4 min-w-0 space-y-3">{pending.slice(0,4).map(x=><Link to={`/reservations?id=${x.id}`} key={x.id} className="pressable-card group flex min-w-0 max-w-full items-center gap-3 overflow-hidden rounded-2xl bg-white/80 p-4 shadow-sm transition hover:bg-coral-50"><span className="icon-shell flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white text-coral-500 shadow-sm transition group-hover:bg-coral-500 group-hover:text-white"><ReservationTypeIcon type={x.type} size={19}/></span><div className="min-w-0 flex-1 overflow-hidden"><p className="truncate font-semibold">{x.name}</p><p className="mt-1 truncate text-xs text-stone-400">{formatDate(x.date)} · {x.location||'地点待定'}</p></div><Badge>{x.type}</Badge></Link>)}</div>:<Link to="/reservations?tab=pending" className="mt-6 block max-w-full truncate text-sm text-stone-400">预约任务已经全部搞定。</Link>}</section>
      <section className="dashboard-section section-card section-sky p-6"><div className="flex min-w-0 items-center justify-between gap-3"><h2 className="min-w-0 font-bold">最近收藏</h2><Link to="/inspirations" className="shrink-0 text-xs font-semibold text-coral-600">灵感库</Link></div>{favorite.length?<div className="mt-4 min-w-0 space-y-4">{favorite.map(x=><div key={x.id} className="min-w-0 max-w-full overflow-hidden border-b border-stone-100 pb-4 last:border-0"><div className="flex min-w-0 items-start justify-between gap-3"><p className="min-w-0 flex-1 break-words font-semibold [overflow-wrap:anywhere]">{x.title}</p><Badge tone="mint">{x.platform}</Badge></div><div className="mt-2 max-w-full overflow-hidden"><LinkButton href={x.url}>{x.platform==='小红书'?'跳转小红书':'打开链接'}</LinkButton></div></div>)}</div>:<p className="mt-6 max-w-full truncate text-sm text-stone-400">还没有收藏的攻略。</p>}</section>
    </div>
  </div>
}
