import { useEffect, useState } from 'react'
import { Edit3, PieChart, Trash2, WalletCards } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import { ExpenseForm } from '../components/ResourceForms'
import { Badge, EmptyState, ErrorBanner, IconButton, Loading, Modal, PageHeader, StatCard } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import { useTrip } from '../contexts/TripContext'
import type { Expense, ExpenseCategory, NewItem } from '../types'
import { formatDate, formatMoney } from '../utils'

export default function Expenses(){
  const {selectedTrip}=useTrip();const trip=selectedTrip!;const tripId=trip.id
  const {data,loading,error,reload}=useLoad(async()=>{const [expenses,itinerary,reservations]=await Promise.all([api.expenses.list({trip_id:tripId}),api.itinerary.list({trip_id:tripId}),api.reservations.list({trip_id:tripId})]);return {trip,expenses,itinerary,reservations}});const [filter,setFilter]=useState('全部'),[editing,setEditing]=useState<Expense|null|undefined>(undefined),[params,setParams]=useSearchParams();useEffect(()=>{if(params.get('new')==='1'){setEditing(null);setParams({}, {replace:true})}},[params,setParams])
  if(loading)return <Loading/>;if(!data)return <ErrorBanner message={error}/>;const items=data.expenses.filter(x=>filter==='全部'||x.category===filter),baseExpenses=data.expenses.filter(x=>(x.currency||'CNY')===data.trip.currency),spent=baseExpenses.reduce((s,x)=>s+Number(x.amount),0),budget=Number(data.trip.total_budget),remaining=budget-spent,percent=budget?Math.min(100,spent/budget*100):0;const cats:('全部'|ExpenseCategory)[]=['全部','交通','住宿','餐饮','门票','购物','其他'];const categoryTotals=Object.fromEntries(cats.slice(1).map(c=>[c,baseExpenses.filter(x=>x.category===c).reduce((s,x)=>s+Number(x.amount),0)]));const currencyTotals=Object.entries(data.expenses.reduce<Record<string,number>>((a,x)=>{const currency=x.currency||'CNY';a[currency]=(a[currency]||0)+Number(x.amount);return a},{}));const groups=items.reduce<Record<string,Expense[]>>((a,x)=>{(a[x.date]??=[]).push(x);return a},{});const save=async(v:NewItem<Expense>)=>{editing?await api.expenses.update(editing.id,v):await api.expenses.create(v);setEditing(undefined);await reload()};const remove=async(x:Expense)=>{if(confirm(`确定删除“${x.title}”吗？`)){await api.expenses.remove(x.id);await reload()}}
  return <div><PageHeader title="旅行记账" description="知道钱花去了哪里，也不让数字偷走旅行的快乐。" action="记一笔" onAction={()=>setEditing(null)}/><ErrorBanner message={error}/>
    <section className="card overflow-hidden p-6 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-stone-500">预算进度</p><p className="mt-2 text-3xl font-bold">{formatMoney(spent,data.trip.currency)} <span className="text-base font-normal text-stone-400">/ {formatMoney(budget,data.trip.currency)}</span></p></div><p className={remaining<0?'font-semibold text-red-500':'font-semibold text-mint-600'}>{remaining<0?'超出预算':'剩余预算'} {formatMoney(Math.abs(remaining),data.trip.currency)}</p></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-stone-100"><div className="h-full rounded-full bg-gradient-to-r from-mint-500 via-skysoft-500 to-coral-500" style={{width:`${percent}%`}}/></div><p className="mt-2 text-right text-xs text-stone-400">已使用 {percent.toFixed(1)}%</p></section>
    {currencyTotals.length>1&&<div className="mt-5 card p-5"><p className="text-sm font-semibold text-stone-500">按币种汇总 <span className="font-normal text-stone-400">· 不自动换算汇率</span></p><div className="mt-3 flex flex-wrap gap-3">{currencyTotals.map(([currency,total])=><span key={currency} className="rounded-xl bg-stone-50 px-4 py-2 text-sm font-bold">{formatMoney(total,currency)}</span>)}</div></div>}
    <div className="mt-5 grid gap-4 sm:grid-cols-3 xl:grid-cols-6">{Object.entries(categoryTotals).map(([c,total])=><StatCard key={c} label={`${c} · ${data.trip.currency}`} value={formatMoney(total,data.trip.currency)} icon={c==='交通'?<WalletCards size={18}/>:<PieChart size={18}/>}/>)}</div>
    <div className="my-6 flex flex-wrap gap-2">{cats.map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-xs font-semibold ${filter===x?'bg-coral-500 text-white':'bg-white text-stone-500 shadow-sm'}`}>{x}</button>)}</div>
    {!items.length?<EmptyState title="还没有消费记录" message="第一杯咖啡、第一张车票，都可以成为旅行的一部分。" action="记一笔" onAction={()=>setEditing(null)}/>:<div className="space-y-6">{Object.entries(groups).map(([date,day])=><section key={date}><div className="mb-3 flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between"><h2 className="font-bold">{formatDate(date,{month:'long',day:'numeric',weekday:'long'})}</h2><div className="flex flex-wrap gap-2 text-sm font-semibold text-stone-500">{Object.entries(day.reduce<Record<string,number>>((a,x)=>{const currency=x.currency||'CNY';a[currency]=(a[currency]||0)+Number(x.amount);return a},{})).map(([currency,total])=><span key={currency}>{formatMoney(total,currency)}</span>)}</div></div><div className="card divide-y divide-stone-100 overflow-hidden">{day.map(x=><div key={x.id} className="flex items-center gap-4 p-4 sm:p-5"><span className="rounded-xl bg-coral-50 p-3 text-coral-600"><WalletCards size={19}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{x.title}</p><Badge tone="stone">{x.category}</Badge><Badge tone="sky">{x.currency||'CNY'}</Badge>{x.is_split&&<Badge tone="mint">AA</Badge>}</div><p className="mt-1 text-xs text-stone-400">{x.payment_method||'未填写支付方式'}</p></div><p className="font-bold">{formatMoney(Number(x.amount),x.currency||'CNY')}</p><div className="hidden sm:block"><IconButton aria-label="编辑" onClick={()=>setEditing(x)}><Edit3 size={17}/></IconButton><IconButton aria-label="删除" onClick={()=>void remove(x)}><Trash2 size={17}/></IconButton></div></div>)}</div></section>)}</div>}
    <Modal open={editing!==undefined} title={editing?'编辑消费':'记一笔'} onClose={()=>setEditing(undefined)}><ExpenseForm key={editing?.id||'new'} item={editing} itinerary={data.itinerary} reservations={data.reservations} tripCurrency={data.trip.currency} tripId={tripId} onSave={save} onCancel={()=>setEditing(undefined)}/></Modal>
  </div>
}
