import { useEffect, useMemo, useState } from 'react'
import { Bus, CalendarDays, Edit3, MapPinned, Plus, Route, TrainFront, Trash2 } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import JourneyMap from '../components/JourneyMap'
import MapPreview, { MapButton, type MapTarget } from '../components/MapPreview'
import { CityForm, PlaceForm, RouteLegForm } from '../components/ResourceForms'
import { Badge, EmptyState, ErrorBanner, IconButton, ImageCover, LinkButton, Loading, Modal, PageHeader } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import type { City, NewItem, Place, PlaceType, Reservation, RouteLeg, TransportMode } from '../types'
import { formatDate } from '../utils'

const placeTypes:('全部'|PlaceType)[]=['全部','酒店','车站','机场','景点','餐厅','商场','其他']

export default function Places(){
  const {data,loading,error,reload}=useLoad(async()=>{const [cities,places,routes,reservations]=await Promise.all([api.cities.list(),api.places.list(),api.routeLegs.list(),api.reservations.list()]);return {cities,places,routes,reservations}})
  const [activeCity,setActiveCity]=useState<number|null|undefined>(undefined),[filter,setFilter]=useState('全部'),[editingPlace,setEditingPlace]=useState<Place|null|undefined>(undefined),[editingCity,setEditingCity]=useState<City|null|undefined>(undefined),[editingRoute,setEditingRoute]=useState<RouteLeg|null|undefined>(undefined),[routeDetail,setRouteDetail]=useState<RouteLeg|null>(null),[mapTarget,setMapTarget]=useState<MapTarget|null>(null),[params,setParams]=useSearchParams()
  useEffect(()=>{if(params.get('new')==='1'){setEditingPlace(null);setParams({}, {replace:true})}},[params,setParams])
  useEffect(()=>{if(data&&activeCity===undefined)setActiveCity(data.cities[0]?.id??null)},[data,activeCity])
  const items=useMemo(()=>data?.places.filter(x=>(!activeCity||x.city_id===activeCity)&&(filter==='全部'||x.type===filter))||[],[data,activeCity,filter])
  if(loading)return <Loading/>;if(!data)return <ErrorBanner message={error}/>
  const city=data.cities.find(x=>x.id===activeCity),placeById=new Map(data.places.map(x=>[x.id,x])),reservationById=new Map(data.reservations.map(x=>[x.id,x]))
  const savePlace=async(v:NewItem<Place>)=>{editingPlace?await api.places.update(editingPlace.id,v):await api.places.create(v);setEditingPlace(undefined);await reload()}
  const saveCity=async(v:NewItem<City>)=>{editingCity?await api.cities.update(editingCity.id,v):await api.cities.create(v);setEditingCity(undefined);await reload()}
  const saveRoute=async(v:NewItem<RouteLeg>)=>{editingRoute?await api.routeLegs.update(editingRoute.id,v):await api.routeLegs.create(v);setEditingRoute(undefined);await reload()}
  const removePlace=async(x:Place)=>{if(confirm(`确定删除“${x.name}”吗？相关路线也会删除。`)){await api.places.remove(x.id);await reload()}}
  const removeCity=async(x:City)=>{if(confirm(`确定删除城市“${x.name}”吗？城市下的地点不会删除，但会变为未分组。`)){await api.cities.remove(x.id);setActiveCity(null);await reload()}}
  const removeRoute=async(x:RouteLeg)=>{if(confirm(`确定删除路线“${x.title}”吗？`)){await api.routeLegs.remove(x.id);setRouteDetail(null);await reload()}}
  const selectMode=async(route:RouteLeg,mode:TransportMode)=>{const {id:_,...payload}=route;const updated=await api.routeLegs.update(route.id,{...payload,selected_mode:mode});setRouteDetail(updated);await reload()}
  return <div><PageHeader title="城市与路线" description="一段大旅程，由途经的城市、地点与连接它们的路线组成。" action="新增地点" onAction={()=>setEditingPlace(null)}/><ErrorBanner message={error}/>
    <section className="card mb-6 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex min-w-0 gap-2 overflow-x-auto pb-1">{data.cities.map((x,index)=><button key={x.id} onClick={()=>setActiveCity(x.id)} className={`flex shrink-0 items-center gap-3 rounded-2xl px-4 py-3 text-left transition ${activeCity===x.id?'bg-stone-900 text-white':'bg-stone-50 text-stone-600 hover:bg-stone-100'}`}><span className={`flex h-7 w-7 items-center justify-center rounded-full text-xs font-bold ${activeCity===x.id?'bg-coral-500':'bg-white'}`}>{index+1}</span><span><b className="block text-sm">{x.name}</b><small className={activeCity===x.id?'text-stone-400':'text-stone-400'}>{x.country||'未填写国家'}</small></span></button>)}</div><div className="flex shrink-0 gap-2"><button className="secondary-btn" onClick={()=>setEditingCity(null)}><Plus size={16}/>新增城市</button>{city&&<><IconButton aria-label="编辑城市" onClick={()=>setEditingCity(city)}><Edit3 size={18}/></IconButton><IconButton aria-label="删除城市" onClick={()=>void removeCity(city)}><Trash2 size={18}/></IconButton></>}</div></div>{city&&<div className="mt-4 flex flex-wrap items-center gap-4 border-t border-stone-100 pt-4 text-sm text-stone-500"><Badge tone="coral">第 {city.order_index+1} 站</Badge>{city.arrival_date&&<span className="flex items-center gap-1.5"><CalendarDays size={15}/>{formatDate(city.arrival_date)}{city.departure_date&&` — ${formatDate(city.departure_date)}`}</span>}{city.note&&<span>{city.note}</span>}</div>}</section>
    <section className="card mb-6 overflow-hidden p-3"><div className="flex flex-col gap-3 px-3 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 font-bold"><MapPinned className="text-coral-500"/>旅程地图</h2><p className="mt-1 text-xs text-stone-400">点击橙色路线查看可选交通方式和已关联预约</p></div><div className="flex gap-2"><button className={`rounded-xl px-3 py-2 text-xs font-semibold ${activeCity===null?'bg-coral-500 text-white':'bg-stone-100'}`} onClick={()=>setActiveCity(null)}>全部城市</button><button className="primary-btn" onClick={()=>setEditingRoute(null)} disabled={data.places.length<2}><Route size={16}/>新增路线</button></div></div><JourneyMap cities={data.cities} places={data.places} routes={data.routes} activeCityId={activeCity??null} onRouteClick={setRouteDetail}/></section>
    <div className="mb-5 flex flex-wrap gap-2">{placeTypes.map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-4 py-2 text-xs font-semibold ${filter===x?'bg-stone-800 text-white':'bg-white text-stone-500 shadow-sm'}`}>{x}</button>)}</div>
    {!items.length?<EmptyState title={city?`${city.name}还没有地点`:'还没有可显示的地点'} message="添加酒店、车站、餐厅或景点，并填写经纬度后即可连成路线。" action="新增地点" onAction={()=>setEditingPlace(null)}/>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map(x=><article key={x.id} className="card overflow-hidden"><ImageCover src={x.image_url} label={x.city||x.type}/><div className="p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-bold">{x.name}</h3><Badge tone="sky">{x.type}</Badge></div>{x.address&&<p className="mt-3 text-sm leading-6 text-stone-500">{x.address}</p>}<div className="mt-5 flex items-center justify-between">{x.map_url?<MapButton target={{title:x.name,url:x.map_url,query:[x.city,x.address].filter(Boolean).join(' ')}} onOpen={setMapTarget}/>:<span className="text-xs text-stone-400">{x.latitude!=null?'已标记坐标':'坐标待补充'}</span>}<div><IconButton aria-label="编辑" onClick={()=>setEditingPlace(x)}><Edit3 size={17}/></IconButton><IconButton aria-label="删除" onClick={()=>void removePlace(x)}><Trash2 size={17}/></IconButton></div></div></div></article>)}</div>}
    <Modal open={editingPlace!==undefined} title={editingPlace?'编辑地点':'新增地点'} onClose={()=>setEditingPlace(undefined)}><PlaceForm key={editingPlace?.id||'new'} item={editingPlace} cities={data.cities} onSave={savePlace} onCancel={()=>setEditingPlace(undefined)}/></Modal>
    <Modal open={editingCity!==undefined} title={editingCity?'编辑城市':'新增城市'} onClose={()=>setEditingCity(undefined)}><CityForm key={editingCity?.id||'new'} item={editingCity} onSave={saveCity} onCancel={()=>setEditingCity(undefined)}/></Modal>
    <Modal open={editingRoute!==undefined} title={editingRoute?'编辑路线':'新增路线'} onClose={()=>setEditingRoute(undefined)}><RouteLegForm key={editingRoute?.id||'new'} item={editingRoute} places={data.places} reservations={data.reservations} onSave={saveRoute} onCancel={()=>setEditingRoute(undefined)}/></Modal>
    <Modal open={Boolean(routeDetail)} title={routeDetail?.title||'路线详情'} onClose={()=>setRouteDetail(null)}>{routeDetail&&<RouteDetail route={routeDetail} from={placeById.get(routeDetail.from_place_id)} to={placeById.get(routeDetail.to_place_id)} reservation={routeDetail.reservation_id?reservationById.get(routeDetail.reservation_id):undefined} onSelect={mode=>void selectMode(routeDetail,mode)} onEdit={()=>{setEditingRoute(routeDetail);setRouteDetail(null)}} onDelete={()=>void removeRoute(routeDetail)}/>}</Modal>
    <MapPreview target={mapTarget} onClose={()=>setMapTarget(null)}/>
  </div>
}

function RouteDetail({route,from,to,reservation,onSelect,onEdit,onDelete}:{route:RouteLeg;from?:Place;to?:Place;reservation?:Reservation;onSelect:(mode:TransportMode)=>void;onEdit:()=>void;onDelete:()=>void}){
  return <div><div className="flex items-center gap-3 rounded-2xl bg-stone-50 p-4"><span className="rounded-xl bg-coral-50 p-3 text-coral-600">{route.selected_mode==='火车'?<TrainFront/>:<Bus/>}</span><div><p className="font-bold">{from?.name||'未知起点'} → {to?.name||'未知终点'}</p><p className="mt-1 text-xs text-stone-400">{route.duration_minutes?`预计 ${route.duration_minutes} 分钟`:'尚未填写预计时间'}</p></div></div><h3 className="mt-6 text-sm font-bold">选择交通方式</h3><div className="mt-3 flex flex-wrap gap-2">{route.transport_modes.map(mode=><button key={mode} onClick={()=>onSelect(mode)} className={`rounded-full px-4 py-2 text-sm font-semibold ${route.selected_mode===mode?'bg-coral-500 text-white':'bg-stone-100 text-stone-600'}`}>{mode}</button>)}</div>{reservation&&<div className="mt-6 rounded-2xl border border-mint-100 bg-mint-50 p-4"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-mint-600">已关联你的{reservation.type}预约</p><p className="mt-1 font-bold">{reservation.name}</p><p className="mt-1 text-sm text-stone-500">{formatDate(reservation.date)} {reservation.time?.slice(0,5)} · {reservation.order_number||'暂无订单号'}</p></div><Badge tone="mint">{reservation.status}</Badge></div>{reservation.booking_url&&<div className="mt-3"><LinkButton href={reservation.booking_url}>查看预约详情</LinkButton></div>}</div>}{route.note&&<p className="mt-5 text-sm leading-6 text-stone-500">{route.note}</p>}<div className="mt-7 flex justify-end gap-3"><button className="secondary-btn text-red-500" onClick={onDelete}>删除路线</button><button className="primary-btn" onClick={onEdit}>编辑路线</button></div></div>
}
