import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, CheckCircle2, Edit3, MapPin, Trash2 } from 'lucide-react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api/client'
import MapPreview, { MapButton, type MapTarget } from '../components/MapPreview'
import { ReservationForm } from '../components/ResourceForms'
import { Badge, EmptyState, ErrorBanner, IconButton, ImageCover, LinkButton, Loading, Modal, PageHeader } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import { useTrip } from '../contexts/TripContext'
import type { NewItem, Reservation, ReservationType } from '../types'
import { formatDate } from '../utils'

export default function Reservations(){
  const {selectedTrip}=useTrip();const tripId=selectedTrip!.id
  const {data,loading,error,reload}=useLoad(async()=>{const [reservations,cities]=await Promise.all([api.reservations.list({trip_id:tripId}),api.cities.list({trip_id:tripId})]);return {reservations,cities}})
  const [tab,setTab]=useState<'booked'|'pending'>('booked'),[filter,setFilter]=useState('全部'),[cityFilter,setCityFilter]=useState<number|null>(null),[editing,setEditing]=useState<Reservation|null|undefined>(undefined),[mapTarget,setMapTarget]=useState<MapTarget|null>(null),[params,setParams]=useSearchParams()
  useEffect(()=>{if(params.get('new')==='1'){setEditing(null);setParams({}, {replace:true})}},[params,setParams])
  useEffect(()=>{const id=Number(params.get('id'));if(id&&data){const target=data.reservations.find(x=>x.id===id);if(target){setTab(target.status==='待预约'?'pending':'booked');if(target.city_id)setCityFilter(target.city_id);setTimeout(()=>document.getElementById(`reservation-${id}`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)}}},[params,data])
  const items=useMemo(()=>data?.reservations.filter(x=>(tab==='pending'?x.status==='待预约':x.status!=='待预约')&&(filter==='全部'||x.type===filter)&&(!cityFilter||x.city_id===cityFilter))||[],[data,tab,filter,cityFilter])
  if(loading)return <Loading/>;if(!data)return <ErrorBanner message={error}/>
  const cityById=new Map(data.cities.map(x=>[x.id,x])),types:('全部'|ReservationType)[]=['全部','酒店','车票','机票','景点','餐厅','其他']
  const save=async(v:NewItem<Reservation>)=>{editing?await api.reservations.update(editing.id,v):await api.reservations.create(v);setEditing(undefined);await reload()}
  const remove=async(x:Reservation)=>{if(confirm(`确定删除“${x.name}”吗？`)){await api.reservations.remove(x.id);await reload()}}
  const mark=async(x:Reservation)=>{const {id:_,...payload}=x;await api.reservations.update(x.id,{...payload,status:'已预约'});await reload()}
  return <div><PageHeader title="预约管理" description="跨城市的车票、酒店与活动预约，都按旅程顺序收好。" action="新增预约" onAction={()=>setEditing(null)}/><ErrorBanner message={error}/>
    <div className="mb-4 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setCityFilter(null)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${cityFilter===null?'bg-stone-900 text-white':'bg-white text-stone-500'}`}>全部城市</button>{data.cities.map((x,index)=><button key={x.id} onClick={()=>setCityFilter(x.id)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-semibold ${cityFilter===x.id?'bg-stone-900 text-white':'bg-white text-stone-500'}`}>{index+1}. {x.name}</button>)}</div>
    <div className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="inline-flex self-start rounded-2xl bg-white p-1 shadow-sm"><button onClick={()=>setTab('booked')} className={`rounded-xl px-5 py-2 text-sm font-semibold ${tab==='booked'?'bg-coral-500 text-white':'text-stone-500'}`}>已预约</button><button onClick={()=>setTab('pending')} className={`rounded-xl px-5 py-2 text-sm font-semibold ${tab==='pending'?'bg-coral-500 text-white':'text-stone-500'}`}>待预约</button></div><div className="flex flex-wrap gap-2">{types.map(x=><button key={x} onClick={()=>setFilter(x)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${filter===x?'bg-stone-800 text-white':'bg-white text-stone-500'}`}>{x}</button>)}</div></div>
    {!items.length?<EmptyState title="这里还没有预约" message="想到要订的跨城车票、酒店或门票，都可以先放在这里。" action="新增预约" onAction={()=>setEditing(null)}/>:<div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{items.map(x=><article id={`reservation-${x.id}`} key={x.id} className={`card overflow-hidden transition ${params.get('id')===String(x.id)?'ring-2 ring-coral-500':''}`}><ImageCover src={x.image_url} label={cityById.get(x.city_id||0)?.name||x.type}/><div className="p-5"><div className="flex items-start justify-between gap-3"><div>{x.city_id&&<p className="mb-1 text-xs font-semibold text-coral-600">{cityById.get(x.city_id)?.name}</p>}<h3 className="text-lg font-bold">{x.name}</h3></div><Badge tone={x.status==='已预约'?'mint':x.status==='待预约'?'coral':'stone'}>{x.status}</Badge></div><div className="mt-4 space-y-2 text-sm text-stone-500"><p className="flex items-center gap-2"><CalendarDays size={15}/>{formatDate(x.date)} {x.time?.slice(0,5)}</p>{x.location&&<p className="flex items-center gap-2"><MapPin size={15}/>{x.location}</p>}{x.order_number&&<p className="text-xs">预约号：{x.order_number}</p>}</div><div className="mt-5 flex flex-wrap items-center gap-4">{x.booking_url&&<LinkButton href={x.booking_url}>{x.status==='待预约'?'去预约':'查看订单'}</LinkButton>}{x.map_url&&<MapButton target={{title:x.name,url:x.map_url,query:x.location}} onOpen={setMapTarget}/>}</div><div className="mt-5 flex items-center justify-between border-t border-stone-100 pt-3">{x.status==='待预约'?<button onClick={()=>void mark(x)} className="inline-flex items-center gap-1.5 text-sm font-semibold text-mint-600"><CheckCircle2 size={16}/>标为已预约</button>:<span/>}<div><IconButton aria-label="编辑" onClick={()=>setEditing(x)}><Edit3 size={17}/></IconButton><IconButton aria-label="删除" onClick={()=>void remove(x)}><Trash2 size={17}/></IconButton></div></div></div></article>)}</div>}
    <Modal open={editing!==undefined} title={editing?'编辑预约':'新增预约'} onClose={()=>setEditing(undefined)}><ReservationForm key={editing?.id||'new'} item={editing} cities={data.cities} tripId={tripId} onSave={save} onCancel={()=>setEditing(undefined)}/></Modal><MapPreview target={mapTarget} onClose={()=>setMapTarget(null)}/>
  </div>
}
