import { useEffect, useRef, useState, type FormEvent } from 'react'
import { DatabaseBackup, Download, RotateCcw, Save, Upload } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { api } from '../api/client'
import { ErrorBanner, FormInput, FormSelect, Loading, PageHeader } from '../components/UI'
import { useLoad } from '../hooks/useLoad'
import { useTrip } from '../contexts/TripContext'
import type { ExportPayload, Trip } from '../types'

export default function Settings(){
  const navigate=useNavigate()
  const {selectedTrip,refreshTrips,trips}=useTrip();const data=selectedTrip!;const loading=false,error='';const [form,setForm]=useState<Omit<Trip,'id'>|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[actionError,setActionError]=useState('');const fileRef=useRef<HTMLInputElement>(null)
  useEffect(()=>{if(data)setForm({name:data.name,start_date:data.start_date,end_date:data.end_date,total_budget:Number(data.total_budget),currency:data.currency})},[data])
  const notice=(value:string)=>{setMessage(value);setActionError('');setTimeout(()=>setMessage(''),3000)}
  const save=async(e:FormEvent)=>{e.preventDefault();if(!form)return;setSaving(true);setActionError('');try{await api.trips.update(data.id,form);notice('旅程设置已保存');await refreshTrips()}catch(e){setActionError(e instanceof Error?e.message:'保存失败')}finally{setSaving(false)}}
  const exportData=async()=>{try{const blob=await api.exportArchive();const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`travel-planner-full-${new Date().toISOString().slice(0,10)}.zip`;a.click();URL.revokeObjectURL(href);notice('完整备份已导出，包含所有 PDF')}catch(e){setActionError(e instanceof Error?e.message:'导出失败')}}
  const importFile=async(file?:File)=>{if(!file)return;try{if(!confirm('导入会替换当前全部旅程、数据和 PDF，确定继续吗？'))return;if(file.name.toLowerCase().endsWith('.zip')){if(file.size>250*1024*1024)throw new Error('ZIP 备份不能超过 250 MB');await api.importArchive(file)}else{const payload=JSON.parse(await file.text()) as ExportPayload;await api.import(payload)}notice('数据与 PDF 恢复成功');await refreshTrips()}catch(e){setActionError(e instanceof Error?e.message:'文件无效或导入失败')}finally{if(fileRef.current)fileRef.current.value=''}}
  const reset=async()=>{if(!confirm('将清空全部旅程、日程、预约、灵感、地点和消费。确定继续吗？'))return;if(!confirm('此操作无法撤销。再次确认清空本地数据？'))return;try{await api.reset();notice('本地数据已清空');await refreshTrips()}catch(e){setActionError(e instanceof Error?e.message:'清空失败')}}
  const removeTrip=async()=>{if(trips.length<=1){setActionError('至少保留一个旅程；可以新建旅程后再删除当前旅程。');return}if(!confirm(`确定删除旅程“${data.name}”及其全部国家、城市、日程和预约吗？`))return;try{await api.trips.remove(data.id);await refreshTrips()}catch(e){setActionError(e instanceof Error?e.message:'删除旅程失败')}}
  if(loading)return <Loading/>;if(!form)return <ErrorBanner message={error}/>
  return <div><PageHeader title="设置" description="调整旅行基本信息，也照看好你的本地数据。" action="导出公开攻略" onAction={()=>navigate('/guide')}/><ErrorBanner message={error||actionError}/>{message&&<div className="mb-5 rounded-xl border border-mint-100 bg-mint-50 px-4 py-3 text-sm font-semibold text-mint-600">{message}</div>}
    <div className="grid gap-6 lg:grid-cols-5"><section className="card p-6 lg:col-span-3"><div className="mb-6 flex items-center gap-3"><span className="rounded-xl bg-coral-50 p-2.5 text-coral-500"><Save size={20}/></span><div><h2 className="font-bold">旅行设置</h2><p className="text-xs text-stone-400">首页和预算统计会使用这些信息</p></div></div><form onSubmit={save}><div className="grid gap-4 sm:grid-cols-2"><div className="sm:col-span-2"><FormInput required label="旅行名称" placeholder="例如：日本关西 8 日游" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><FormInput required type="date" label="开始日期" value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/><FormInput required type="date" label="结束日期" value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/><FormInput required type="number" min="0" step="0.01" label="总预算" value={form.total_budget} onChange={e=>setForm({...form,total_budget:Number(e.target.value)})}/><FormSelect label="预算货币" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}>{[['CNY','人民币'],['USD','美元'],['EUR','欧元'],['GBP','英镑'],['JPY','日元'],['HKD','港币'],['KRW','韩元'],['THB','泰铢'],['SGD','新加坡元'],['AUD','澳元'],['CAD','加元'],['CHF','瑞士法郎']].map(([value,label])=><option key={value} value={value}>{label} · {value}</option>)}</FormSelect></div><button className="primary-btn mt-6" disabled={saving}>{saving?'保存中…':'保存设置'}</button></form></section>
      <section className="card p-6 lg:col-span-2"><div className="mb-6 flex items-center gap-3"><span className="rounded-xl bg-mint-50 p-2.5 text-mint-600"><DatabaseBackup size={20}/></span><div><h2 className="font-bold">数据管理</h2><p className="text-xs text-stone-400">备份、恢复或重新开始</p></div></div><div className="space-y-3"><button onClick={()=>void exportData()} className="flex w-full items-center gap-3 rounded-2xl border border-stone-100 p-4 text-left transition hover:bg-stone-50"><Download className="text-skysoft-500"/><span><b className="block text-sm">导出完整备份 ZIP</b><small className="text-stone-400">包含全部旅程数据和预约 PDF</small></span></button><button onClick={()=>fileRef.current?.click()} className="flex w-full items-center gap-3 rounded-2xl border border-stone-100 p-4 text-left transition hover:bg-stone-50"><Upload className="text-mint-600"/><span><b className="block text-sm">导入备份恢复</b><small className="text-stone-400">支持完整 ZIP 或旧版 JSON</small></span></button><input ref={fileRef} className="hidden" type="file" accept="application/zip,.zip,application/json,.json" onChange={e=>void importFile(e.target.files?.[0])}/><button onClick={()=>void removeTrip()} className="flex w-full items-center gap-3 rounded-2xl border border-amber-100 p-4 text-left text-amber-700 transition hover:bg-amber-50"><RotateCcw/><span><b className="block text-sm">删除当前旅程</b><small className="text-amber-600">只删除“{data.name}”及其下属内容</small></span></button><button onClick={()=>void reset()} className="flex w-full items-center gap-3 rounded-2xl border border-red-100 p-4 text-left text-red-600 transition hover:bg-red-50"><RotateCcw/><span><b className="block text-sm">清空全部数据库</b><small className="text-red-400">删除所有旅程，需要两次确认</small></span></button></div><p className="mt-5 rounded-xl bg-stone-50 p-3 text-xs leading-5 text-stone-400">完整 ZIP 会一起备份 PDF。建议旅程有重要修改后及时导出。</p></section></div>
  </div>
}
