import { useState, type ReactNode } from 'react'
import { ArrowLeft, Backpack, CalendarDays, FileDown, MapPinned, Route, ShieldCheck, Sparkles } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../api/client'
import { ErrorBanner, Loading } from '../components/UI'
import { useTrip } from '../contexts/TripContext'
import { useLoad } from '../hooks/useLoad'
import { formatDate } from '../utils'
import { printPublicGuide } from '../utils/printGuide'

export default function PublicGuide(){
  const {selectedTrip}=useTrip();const trip=selectedTrip!;const tripId=trip.id;const [printing,setPrinting]=useState(false)
  const {data,loading,error}=useLoad(async()=>{const [destinations,cities,itinerary,places,routes,checklist]=await Promise.all([api.destinations.list({trip_id:tripId}),api.cities.list({trip_id:tripId}),api.itinerary.list({trip_id:tripId}),api.places.list({trip_id:tripId}),api.routeLegs.list({trip_id:tripId}),api.checklist.list({trip_id:tripId})]);return {destinations,cities,itinerary,places,routes,checklist}})
  if(loading)return <Loading/>;if(!data)return <ErrorBanner message={error}/>
  const cityById=new Map(data.cities.map(x=>[x.id,x])),placeById=new Map(data.places.map(x=>[x.id,x]))
  const days=Array.from(new Set(data.itinerary.map(x=>x.date))).sort()
  const print=async()=>{setPrinting(true);try{await printPublicGuide(`${trip.name}-公开攻略`)}finally{setPrinting(false)}}
  return <div className="public-guide-page min-w-0"><div className="no-print mb-5 flex flex-wrap items-center justify-between gap-3"><Link to="/settings" className="secondary-btn"><ArrowLeft size={17}/>返回设置</Link><button onClick={()=>void print()} disabled={printing} className="primary-btn"><FileDown size={17}/>{printing?'正在打开打印服务':'打印 / 保存为 PDF'}</button></div>
    <div className="no-print mb-5 flex items-start gap-3 rounded-2xl border border-mint-100 bg-mint-50 p-4 text-sm leading-6 text-mint-800"><ShieldCheck className="mt-0.5 shrink-0" size={20}/><p><b>隐私安全的公开版本：</b>不会导出预算、支出、预约号、预订链接、票据附件、清单完成状态或私人备注。选择打印窗口中的“另存为 PDF”即可分享给未安装应用的同行人。</p></div>
    <article className="guide-sheet mx-auto overflow-hidden rounded-[2rem] border border-stone-100 bg-white shadow-card">
      <header className="guide-cover relative overflow-hidden bg-[#292824] px-7 py-12 text-white sm:px-12 sm:py-16"><div className="absolute -right-20 -top-20 h-60 w-60 rounded-full bg-coral-500/20 blur-3xl"/><div className="absolute -bottom-20 left-20 h-48 w-48 rounded-full bg-mint-500/15 blur-3xl"/><div className="relative"><p className="text-xs font-bold uppercase tracking-[.28em] text-coral-400">Public travel guide</p><h1 className="mt-4 text-3xl font-extrabold sm:text-5xl">{trip.name}</h1><p className="mt-4 flex items-center gap-2 text-sm text-stone-300"><CalendarDays size={17}/>{formatDate(trip.start_date,{year:'numeric',month:'long',day:'numeric'})} — {formatDate(trip.end_date,{year:'numeric',month:'long',day:'numeric'})}</p><div className="mt-7 flex flex-wrap gap-2">{data.destinations.map(x=><span key={x.id} className="rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-xs font-semibold">{x.name}</span>)}{data.cities.map(x=><span key={x.id} className="rounded-full border border-mint-500/25 bg-mint-500/10 px-3 py-1.5 text-xs font-semibold text-mint-100">{x.name}</span>)}</div></div></header>
      <div className="space-y-10 px-6 py-9 sm:px-12 sm:py-12">
        <GuideSection icon={<CalendarDays/>} eyebrow="DAY BY DAY" title="逐日行程"><div className="space-y-7">{days.length?days.map(date=><section key={date} className="guide-day"><div className="mb-3 flex items-baseline justify-between border-b border-stone-100 pb-2"><h3 className="text-lg font-bold">{formatDate(date,{month:'long',day:'numeric',weekday:'long'})}</h3><span className="text-xs text-stone-400">{date}</span></div><div className="space-y-3">{data.itinerary.filter(x=>x.date===date).map(item=><div key={item.id} className="grid grid-cols-[3.5rem_1fr] gap-3"><time className="pt-1 text-sm font-bold text-coral-600">{item.start_time.slice(0,5)}</time><div className="min-w-0 rounded-2xl bg-stone-50 p-4"><div className="flex flex-wrap items-center gap-2"><h4 className="font-bold">{item.title}</h4><span className="rounded-full bg-white px-2 py-1 text-[10px] font-bold text-stone-500">{item.type}</span>{item.city_id&&<span className="text-xs text-mint-700">{cityById.get(item.city_id)?.name}</span>}</div>{item.location&&<p className="mt-2 text-sm text-stone-500">地点：{item.location}</p>}</div></div>)}</div></section>):<p className="text-sm text-stone-400">还没有添加日程。</p>}</div></GuideSection>
        <GuideSection icon={<Route/>} eyebrow="ROUTE" title="移动路线"><div className="grid gap-3 sm:grid-cols-2">{data.routes.length?data.routes.map(route=><div key={route.id} className="guide-block rounded-2xl border border-stone-100 p-4"><h3 className="font-bold">{route.title}</h3><p className="mt-2 text-sm text-stone-500">{placeById.get(route.from_place_id)?.name||'起点'} → {placeById.get(route.to_place_id)?.name||'终点'}</p><p className="mt-2 text-xs text-stone-400">{route.selected_mode||route.transport_modes.join(' / ')||'交通方式待定'}{route.duration_minutes?` · 约 ${route.duration_minutes} 分钟`:''}</p></div>):<p className="text-sm text-stone-400">还没有添加移动路线。</p>}</div></GuideSection>
        <GuideSection icon={<MapPinned/>} eyebrow="PLACES" title="地点清单"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{data.places.length?data.places.map(place=><div key={place.id} className="guide-block rounded-2xl bg-stone-50 p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-coral-600">{place.type}</p><h3 className="mt-1 font-bold">{place.name}</h3><p className="mt-1 text-xs text-stone-400">{place.city_id?cityById.get(place.city_id)?.name:place.city||'城市待定'}</p></div>):<p className="text-sm text-stone-400">还没有收藏地点。</p>}</div></GuideSection>
        <GuideSection icon={<Backpack/>} eyebrow="PREPARATION" title="公开准备清单"><div className="grid gap-5 sm:grid-cols-2">{(['行李','待办'] as const).map(kind=><div key={kind} className="guide-block rounded-2xl border border-stone-100 p-5"><h3 className="font-bold">{kind==='行李'?'行李建议':'出发前准备'}</h3><ul className="mt-3 space-y-2 text-sm text-stone-600">{data.checklist.filter(x=>x.kind===kind).map(item=><li key={item.id} className="flex items-start gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-mint-500"/><span>{item.title}{item.quantity>1?` × ${item.quantity}`:''}<small className="ml-2 text-stone-400">{item.category}</small></span></li>)}</ul>{!data.checklist.some(x=>x.kind===kind)&&<p className="mt-3 text-sm text-stone-400">暂无项目</p>}</div>)}</div></GuideSection>
        <footer className="flex items-center gap-2 border-t border-stone-100 pt-6 text-xs text-stone-400"><Sparkles size={14} className="text-coral-500"/>由“旅途”生成的公开攻略 · 已自动排除个人与财务信息</footer>
      </div>
    </article>
  </div>
}

function GuideSection({icon,eyebrow,title,children}:{icon:ReactNode;eyebrow:string;title:string;children:ReactNode}){return <section className="guide-section"><div className="mb-5 flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-coral-50 text-coral-500">{icon}</span><div><p className="text-[10px] font-bold tracking-[.2em] text-stone-400">{eyebrow}</p><h2 className="text-xl font-extrabold">{title}</h2></div></div>{children}</section>}
